# Generated by Django 5.0.2 on 2024-02-29 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_key_encryptionkey_encryption_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionkey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='encryptionkey',
            name='encrypted_text',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
