# Generated by Django 5.0.2 on 2024-02-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_encryptionkey_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
